package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.layout.VBox;
import javafx.stage.Modality;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

import java.io.IOException;
import java.util.*;

public class MainSceneController {
	// ---------------Logic Attribute------------//
	private Verwaltung myVerwaltung;
	
	// --------------- fx_ids -------------------//
	
	// Main Scene:
	@FXML
	private Button gesamtkorb;
	@FXML
	private Button korb_anlegen;
	@FXML
	private VBox displayBox;
	
	
	//----------------Events---------------//
	
	// Main Scene: 

	// Event Listener on Button[#gesamtkorb].onAction
	@FXML
	public void viewAlleKorb(ActionEvent event) {
		// TODO Autogenerated
		
	}
	// Event Listener on Button[#korb_anlegen].onAction
	@FXML
	public void neuWarenkorbErstellen(ActionEvent event) throws IOException {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("KategorieAuswahl.fxml"));
		Parent root = loader.load();
		KategorieAuswahlController controller = loader.getController();
		controller.setVerwaltung(myVerwaltung);
		
		Stage stage = new Stage();
        stage.initModality(Modality.APPLICATION_MODAL);
        stage.setScene(new Scene(root));
        stage.showAndWait();
		if(controller.getWarenkorb()!= null) myVerwaltung.addWarenkorb(controller.getWarenkorb()) ;
			
	}
	
	@FXML
	public void initialize () {
		myVerwaltung = new Verwaltung();
	}
	
}
