package application;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.event.ActionEvent;
import java.util.*;

public class MainSceneController {
	private static Verwaltung myVerwaltung = new Verwaltung();
	@FXML
	private Button gesamtkorb;
	@FXML
	private Button korb_anlegen;

	// Event Listener on Button[#gesamtkorb].onAction
	@FXML
	public void viewAlleKorb(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#korb_anlegen].onAction
	@FXML
	public void neuWarenkorbErstellen(ActionEvent event) {
		myVerwaltung.addWarenkorb(new Warenkorb());
		
	}
}
