package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ChoiceBox;
import javafx.scene.control.Label;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.VBox;
import javafx.stage.Modality;
import javafx.stage.Stage;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import java.io.IOException;

public class MainSceneController {
	// ---------------Logic Attribute------------//
	private Verwaltung myVerwaltung;
	private Warenkorb selectedWarenkorb;
	
	// --------------- fx_ids -------------------//
	
	// Main Scene:
	@FXML
	private Button gesamtkorb;
	@FXML
	private Button korb_anlegen;
	@FXML
	private GridPane displayBox;
	@FXML
	private ChoiceBox<Warenkorb> cbWarenkorb;
	
	
	
	//----------------Events---------------//


	// Event Listener on Button[#gesamtkorb].onAction
	@FXML
	public void viewAlleKorb(ActionEvent event) {
		// TODO Autogenerated
		
	}
	// Event Listener on Button[#korb_anlegen].onAction
	@FXML
	public void neuWarenkorbErstellen(ActionEvent event) throws IOException {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("KategorieAuswahl.fxml"));
		Parent root = loader.load();
		KategorieAuswahlController controller = loader.getController();
		controller.setVerwaltung(myVerwaltung);
		
		Stage stage = new Stage();
        stage.initModality(Modality.APPLICATION_MODAL);
        stage.setScene(new Scene(root));
        stage.showAndWait();
		if(controller.getWarenkorb()!= null) {
			myVerwaltung.addWarenkorb(controller.getWarenkorb());
			cbWarenkorb.getItems().add(controller.getWarenkorb());
		} 
			
	}
	@FXML
	public void selectWarenkorb(ActionEvent event) {
		int selectedIndex = cbWarenkorb.getSelectionModel().getSelectedIndex();
		int index = (selectedIndex < 0) ? 0: selectedIndex;
		this.selectedWarenkorb = myVerwaltung.getWarenkorben().get(index);
	    

	    System.out.println("Selection made: [" + index + "] " + this.selectedWarenkorb);
	}
	
	public void displayWaren() {
		String number = "3";
		//ObservableList<VBox> stuff = FXCollections.observableArrayList();
		for(int i = 1; i<=12; i++) {
			VBox box = new VBox();
			Label name = new Label("Hello"+i);
			Label price = new Label(number+" €");
			Button button1 = new Button("ADD");
			box.getChildren().addAll(name,price,button1);
			int[] koordinate = this.getCoordinates(i);
			displayBox.add(box, koordinate[1], koordinate[0]);
		}
					
	}
	
	public int[] getCoordinates(int sum) {
		int[] koordinate = {0,0};
		if(sum<=4) {
			koordinate[0] = 0;
			koordinate[1] = sum - 1;
		} else if(sum<=8) {
			koordinate[0] = 1;
			koordinate[1] = sum - 5;
		}else {
			koordinate[0] = 2;
			koordinate[1] = sum - 9;
		}
		return koordinate;
	}
	
	@FXML
	public void initialize () {
		myVerwaltung = new Verwaltung();
		myVerwaltung.addWarenkorb(new Warenkorb("Standard",0));
		cbWarenkorb.getItems().addAll(myVerwaltung.getWarenkorben());
		cbWarenkorb.setValue(myVerwaltung.getWarenkorben().get(0));
		displayWaren();
		
		
	}
	
}
